databases:
  - name: bulbulator
    databaseName: bulbulator
    user: bulbulator

services:
  - type: web
    name: bulbulator
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bulbulator
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
